version: 0.2

env:
  parameter-store:
    BUCKET: /codebuild/bucketName

phases:
  install:
    commands:
        - npm install
  build:
    commands:
        - npm run build
  post_build:
    commands:
        - aws s3 sync build/ s3://$BUCKET
